name: Angular Build

# Trigger the workflow on push or pull request events to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      # Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Check linting
      - name: Lint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm run test:ci

      # Build the project
      - name: Build
        run: npm run build